### ISSUE TITLE
Disable module name format requirement

### ISSUE THREAD

**Issue by robertlabrie** [puppetlabs/pdk-planning#19]
`process_name` could be re-worked to make "Field must be a dash-separated user name and module name." optional. Our modules are maintained by a team of dozens of people who rotate in and out of the company, these modules will never ever ever ever ever be released to the public -- this restriction is silly.

Worst still, even if you do `pdk validate puppet` it still tries to parse the metadata and blows up, even if you didn't want to validate the metadata.

**Comment by scotje** [comment]
Hello and thank you for your suggestion! Sorry for the delayed response!

I don't think it's an undue burden to include a namespace (such as your company name) as part of the module name in `metadata.json`. You can create an account on Forge to "reserve" this namespace even if you never publish any content under it. 

The namespace has been a required part of the module name according to all published specifications for metadata.json that I am aware of. Even if PDK made this optional, you never know when you will run into another tool that also assumes the metadata.json will comply with the published documentation/specs.

For those reasons I don't think this is something we will make optional right now. If there is some reason that it is not feasible for you to add a namespace to the affected modules, please let us know of those specific circumstances and we can evaluate other options.

Thanks!

https://puppet.com/docs/puppet/6.4/modules_metadata.html#reference-4908
https://forgeapi.puppet.com/schemas/module.json
