### ISSUE TITLE
PDK config & cache files

### ISSUE THREAD

**Issue by ardrigh** [puppetlabs/pdk-planning#26]
I know there is already RFC for adding configuration commands to PDK, but I would also like to suggest going forward that PDK better supports use of XDG directories where they exist.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

>  The XDG Base Directory Specification is based on the following concepts:
>
>    There is a single base directory relative to which user-specific data files should be written. This directory is defined by the environment variable $XDG_DATA_HOME.
>
>    There is a single base directory relative to which user-specific configuration files should be written. This directory is defined by the environment variable $XDG_CONFIG_HOME.
>
>    There is a set of preference ordered base directories relative to which data files should be searched. This set of directories is defined by the environment variable $XDG_DATA_DIRS.
>
>    There is a set of preference ordered base directories relative to which configuration files should be searched. This set of directories is defined by the environment variable $XDG_CONFIG_DIRS.
>
>    There is a single base directory relative to which user-specific non-essential (cached) data should be written. This directory is defined by the environment variable $XDG_CACHE_HOME.
>
>    There is a single base directory relative to which user-specific runtime files and other file objects should be placed. This directory is defined by the environment variable $XDG_RUNTIME_DIR. 

Currently in Fedora I have a `~/.pdk` directory which could have a number of things added to it, either cache files or templates or other configuration.

It would be nice if PDK made use of the `~/.config`, `~/.cache`, or the `~/.local` directories for the various files it needs or creates.

It makes it much easier to backup `~/.config` for the files I need and not capture a lot of files I don`t need.

This may need to be reflected in the packaging for distributions that support use XDG directories (which should be most of them).

**Comment by scotje** [comment]
This seems like a good idea to me, I think we just need to figure out what the upgrade process would look like for existing users and what the story would be for platforms that haven't adopted the spec. It sounds like that may just be Windows which already has it's own patterns for user/app-level data and config.

**Comment by ardrigh** [comment]
@scotje it might not be something to push existing users through, but provide documentation on how to move manually? Unless you want to consider something like `pdk config update` to automate that process.

It would be good to see this adopted for new users, or people who reinstall ocassionally like myself

**Comment by scotje** [comment]
While `pdk config` has not yet been fully implemented, the backend has started to be added and is using `XDG_CONFIG_HOME` on non-Windows platforms: https://github.com/puppetlabs/pdk/blob/master/lib/pdk/util.rb#L109-L116
