### ISSUE TITLE
Add VSCode recommended extensions file

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/pdk-planning#32]
Adding a `.vscode` folder with an `extensions.json` file listing recommended extensions would be a good way of getting a user up and running quickly using the PDK, This would help out first time users as well as users wanting to quickly setup a new machine.

There are many extensions I would recommend, but I think this list would be a good minimum without imposing opinions on users:

```
{
  "recommendations": [
    "jpogran.puppet-vscode",
    "rebornix.Ruby"
  ]
}
```

**Comment by TJM** [comment]
Please add something to:

* Highlight trailing spaces, Example: `shardulm94.trailing-spaces`
* Highlight "bad" spaces (unicode nbsp) (we get these when people copy code from something like HipChat), Example: `wengerk.highlight-bad-chars`
* Auto Alignment (if we can't do this in the puppet module yet), Example: `wwm.better-align`

**Comment by jpogran** [comment]
One or two of those can be controlled by vscode settings, at the risk of instigating a `tabs vs spaces` war, would adding a `settings.json` be a step too far?

The Puppet Extension already ships with these defaults that are overridden by user/workspace settings:

```
"configurationDefaults": {
  "files.encoding": "utf8",
  "files.associations": [
    ".pp",
    ".epp"
  ],
  "[puppet]": {
    "editor.tabSize": 2,
    "editor.insertSpaces": true,
    "files.insertFinalNewline": true
  }
},
```

**Comment by DavidS** [comment]
Where would the `.vscode` directory go? Do you have a link handy describing how that works in VSCode?

**Comment by TJM** [comment]
Pretty sure it goes into the root of the repo (module)

**Comment by jpogran** [comment]
VSCode has a concept of global and workspace (think project/folder) scoped settings. The `.vscode` directory is at the root of the solution folder, and contains `extensions.json` (workspace recommended extensions), `settings.json` (workspace settings) and `tasks.json` (workspace commands). 

- Workspace recommended extensions [documentation](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions) 
- Setting file locations [documentation](https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations)

**Comment by scotje** [comment]
This sounds good to me!

Generally we want to improve users ability to opt in or out of some of these types of things (various CI, version control, and editor configs) so that they don't have to always be adding a `.sync.yml` entry to remove what they don't want after the fact, but that desire should not prevent us from adding this to the template at the current time.

**Comment by scotje** [comment]
(Also, this is a minor enough change that I don't see the need for an RFC, so feel free to PR the pdk-templates repo.)

**Comment by jpogran** [comment]
Created PR https://github.com/puppetlabs/pdk-templates/pull/256

**Comment by scotje** [comment]
The PR has been merged into pdk-templates
