### ISSUE TITLE
Fedora 30 package

### ISSUE THREAD

**Issue by buckaroogeek** [puppetlabs/pdk-planning#35]
Could the team please release the Fedora 30 package version of the PDK? Bold, and puppet agent are now available.

thank you

Brad

**Comment by scotje** [comment]
@buckaroogeek This work is currently in progress (https://tickets.puppetlabs.com/browse/PDK-1397) and we most likely will have Fedora 30 packages for the next scheduled PDK release in a couple weeks.

**Comment by scotje** [comment]
Fedora 30 packages are available as of PDK 1.12.0, the download page hasn't been updated yet but this link (https://pm.puppet.com/cgi-bin/pdk_download.cgi?dist=fedora&rel=30&arch=x86_64&ver=latest) will direct download the packages or you can add the `puppet-tools` Yum repo for Fedora 30 (http://yum.puppet.com/puppet-tools-release-fedora-30.noarch.rpm) and then `yum install pdk`.
