### ISSUE TITLE
RFC002 - pdk config - Does not support non-String values

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/pdk-planning#64]
## Describe the Bug

Currently the `pdk config` [RFC](https://github.com/puppetlabs/pdk-planning/blob/84d03b997a7e7959b12ed1887cb3bbbb9d5d6710/RFCs/0002-add-pdk-config.md) only gives examples for string type setting values. However what if I need to add a numeric?

There is no way to pass in, or tell PDK, that the datatype is not a string.

## Possible solutions

1.  Could add a `--type`  parameter but this feels like it could be a problem to map/convert all of the ruby types. (Boolean, String, Array, Hash)

2. Could add a `--as-json` so PDK would interpret the value as a JSON compatible string type and then use the `JSON::Parse` to convert it into a comptible ruby type e.g.

`--as-json 2`   would be a an integer of 2

`--as-json true`   would be a boolean of True

`--as-json '"string"'`   would be a string (This is a redundant as without `--as-json` everything would be a string

`--as-json '[1,2,3]'`   would be an array of integer

`--as-json '[1, "abc", 3]'`   would be an array of mixed types

and so-on   (Hashes could also be done)

## Other information

This would supercede the `--add` parameter as now it would be passing it a Type instead of assuming it's an array of string.

**Comment by scotje** [comment]
Do we have to solve this during `set` invocation right now? Since people can always manually fiddle with their config files, it seems like we are going to have to do type-coercion or validation when using values from the config file anyway and can always throw an error at that point.

So for now, can we just accept everything as a string?

In the near future when we can implement schema validation for the config, it will be easy to check the values at `set`-time to ensure they can be coerced to the schema-defined type.

**Comment by scotje** [comment]
If we do decide we need to solve this now, I would definitely lean towards an optional `--type` argument, basically just copy `git config` here: https://git-scm.com/docs/git-config#Documentation/git-config.txt---typelttypegt

**Comment by glennsarti** [comment]
> Do we have to solve this during set invocation right now? 

Strictly speaking no, nut it would mean implementing `--add` which would become deprecated very quickly. And I'd rather avoid work which will be deleted.

>  like we are going to have to do type-coercion or validation...

We already get most of that already: Type co-ercion from JSON/YAML parsing and validation via the `setting .validate` method.

**Comment by glennsarti** [comment]
Perhaps a halfway, would be to at least have type coercion for `array`, `boolean` and `number`?

That would stop the need to implement `--add` and gives the bare minimum types?

Note - We kinda get Hash types "by default" due to my current implementation

**Comment by scotje** [comment]
> Strictly speaking no, but it would mean implementing --add which would become deprecated very quickly. And I'd rather avoid work which will be deleted.

I'm not following why `--add` would be deprecated? It does not seem preferable to me to force users to serialize arrays by hand in the CLI to manage setting lists.

Whether or not we support setting/replacing the entire value of a list in one invocation is another question, but I don't think it should be the only way of dealing with lists via the CLI.
