### ISSUE TITLE
Include epp/erb/yaml validator

### ISSUE THREAD

**Issue by scotje** [puppetlabs/pdk-planning#7]
_From @dan-wittenberg on August 12, 2017 20:15_

Since yaml files are used a lot in hiera there should be a validator for .yaml files

_Copied from original issue: puppetlabs/pdk#246_

**Comment by scotje** [comment]
_From @DavidS on August 15, 2017 14:47_

This is now tracked internally as https://tickets.puppetlabs.com/browse/PDK-421

**Comment by bmjen** [comment]
Yaml validation has been implemented and released with PDK 1.9.0

**Comment by bmjen** [comment]
EPP/ERB tracked in #8 .
