### ISSUE TITLE
Fedora 31 and 32 repos? Ubuntu 19.04, 19.10, 20.04 repos?

### ISSUE THREAD

**Issue by DavidRedstone** [puppetlabs/pdk-planning#73]
## Use Case
Fedora 31 and 32 users, who use Puppet & PDK
Ubuntu 18.10, 19.04, 19.10, 20.04 users...

## Describe the Solution You Would Like
Puppet repos for modern Linux OS

## Describe Alternatives You've Considered
The PDK install page only goes up to Fedora 30 (which was released 1 year ago) and Ubuntu 18.04
https://puppet.com/docs/pdk/1.x/pdk_install.html

This page is also missing releases for the latest OSes
https://puppet.com/try-puppet/puppet-development-kit/

Should I be installing the F30 and Ubuntu 18.04 versions?

## Additional Context
I recently upgraded to the Latest Fedora and Ubuntu on my PCs. VS Code tells me I need to upgrade PDK, but there is no repo. sudo dnf upgrade pdk shows nothing new.

[dave@pcf ~]$ pdk --version
1.17.0

[dave@pcf ~]$ sudo dnf upgrade pdk
Last metadata expiration check: 2:38:43 ago on Fri 15 May 2020 15:27:20.
Dependencies resolved.
Nothing to do.
Complete!

Attempt to get repo... doesn't exist
[dave@pcf yum.repos.d]$ sudo rpm -Uvh https://yum.puppet.com/puppet-tools-release-fedora-32.noarch.rpm
Retrieving https://yum.puppet.com/puppet-tools-release-fedora-32.noarch.rpm
curl: (22) The requested URL returned error: 404 
error: skipping https://yum.puppet.com/puppet-tools-release-fedora-32.noarch.rpm - transfer failed

There are no repos for the most recent releases of Fedora and Ubuntu...

https://yum.puppet.com/
  | puppet-release-fedora-27.noarch.rpm | 2019-06-19 11:54:49 | 14.0KiB |  
  | puppet-release-fedora-28.noarch.rpm | 2020-03-17 15:15:33 | 14.2KiB |  
  | puppet-release-fedora-29.noarch.rpm | 2020-03-17 15:15:31 | 14.2KiB |  
  | puppet-release-fedora-30.noarch.rpm | 2020-03-17 15:15:32 | 14.2KiB |  
  | puppet-release-fedora-31.noarch.rpm | 2020-03-17 15:15:34 | 13.9KiB |  

https://apt.puppet.com/
  | puppet-release-bionic.deb | 2020-03-17 15:15:43 | 11.4KiB |  
  | puppet-release-buster.deb | 2020-03-17 15:15:45 | 11.5KiB |  
  | puppet-release-cumulus.deb | 2018-09-18 10:45:05 | 9.5KiB |  
  | puppet-release-focal.deb | 2020-04-30 11:30:48 | 11.4KiB |  
  | puppet-release-jessie.deb | 2020-03-17 15:15:42 | 11.5KiB |  
  | puppet-release-stretch.deb | 2020-03-17 15:15:47 | 11.4KiB |  
  | puppet-release-trusty.deb | 2020-03-17 15:15:44 | 11.4KiB |  
  | puppet-release-xenial.deb | 2020-03-17 15:15:41 | 11.4KiB

Cheers

**Comment by scotje** [comment]
We'll try to get the new Fedora builds added soon, along with Ubuntu 20.04. Typically we have only packaged for Ubuntu LTS releases but the packages have generally worked on the interim releases as well.

**Comment by DavidRedstone** [comment]
2 months have passed. Is there any update on when there will be packages for Ubuntu 20/04 LTS and Fedora 32?
Thanks

**Comment by scotje** [comment]
Hi David, the 1.18.1 release includes packages for Ubuntu 20.04 (focal), we haven't gotten them added to the download web page yet, but it should be available in the repos. 

Fedora 32 is currently waiting on some packaging tooling fixes, but should be available soon.

**Comment by DavidRedstone** [comment]
Thank you 😁
