### ISSUE TITLE
`pdk release` should be able to use an env var for the PuppetForge API token parameter

### ISSUE THREAD

**Issue by sgnn7** [puppetlabs/pdk-planning#74]
## Use Case

We have an internal multi-tenant Jenkins-based CI environment where we are proactively trying to prevent information disclosure. The current `pdk release` CLI requires a PuppetForge `--forge-token` and this value cannot be provided in any other way than interactively (which we cannot do in CI env). Ideally we would be able to pass this credential to the launched process via an environment variable to prevent potential disclosure vectors in a multi-tenant env.

## Describe the Solution You Would Like
`pdk release` can use an env var (eg. `PDK_FORGE_TOKEN`) as a substitute for the `--forge-token` parameter.

## Describe Alternatives You've Considered
There's really not a lot of options here. Config files can be used too but they're harder to automate and they remain on-disk. Other novel options may be better but they're orders of magnitude more difficult.

**Comment by scotje** [comment]
See https://github.com/puppetlabs/pdk/pull/913

**Comment by sgnn7** [comment]
@scotje 👍 I might as well close this issue. Thanks!
