### ISSUE TITLE
Include erb validator

### ISSUE THREAD

**Issue by scotje** [puppetlabs/pdk-planning#8]
_From @dan-wittenberg on August 12, 2017 20:16_

Since templates are pretty important erb and epp should both include validators

_Copied from original issue: puppetlabs/pdk#247_

**Comment by scotje** [comment]
This is a near-term priority so it would be good to get an RFC written. I think the RFC can be pretty straightforward since this functionality will mirror the existing validators.

**Comment by glennsarti** [comment]
https://tickets.puppetlabs.com/browse/PDK-421 is closed.  EPP validation will come in the next release (1.12.0 or 1.11.1)

**Comment by jpogran** [comment]
This has been implemented
